package android.zhixun.uiho.com.gissystem.greendao_gen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android.zhixun.uiho.com.gissystem.flux.models.CRCheckPersonModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CRCHECK_PERSON_MODEL".
*/
public class CRCheckPersonModelDao extends AbstractDao<CRCheckPersonModel, Long> {

    public static final String TABLENAME = "CRCHECK_PERSON_MODEL";

    /**
     * Properties of entity CRCheckPersonModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CRKey = new Property(1, long.class, "CRKey", false, "CRKEY");
        public final static Property UserID = new Property(2, long.class, "userID", false, "USER_ID");
    }


    public CRCheckPersonModelDao(DaoConfig config) {
        super(config);
    }
    
    public CRCheckPersonModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CRCHECK_PERSON_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CRKEY\" INTEGER NOT NULL ," + // 1: CRKey
                "\"USER_ID\" INTEGER NOT NULL );"); // 2: userID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CRCHECK_PERSON_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CRCheckPersonModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCRKey());
        stmt.bindLong(3, entity.getUserID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CRCheckPersonModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCRKey());
        stmt.bindLong(3, entity.getUserID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CRCheckPersonModel readEntity(Cursor cursor, int offset) {
        CRCheckPersonModel entity = new CRCheckPersonModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // CRKey
            cursor.getLong(offset + 2) // userID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CRCheckPersonModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCRKey(cursor.getLong(offset + 1));
        entity.setUserID(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CRCheckPersonModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CRCheckPersonModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CRCheckPersonModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
