package android.zhixun.uiho.com.gissystem.greendao_gen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android.zhixun.uiho.com.gissystem.flux.models.CRResultTypeModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CRRESULT_TYPE_MODEL".
*/
public class CRResultTypeModelDao extends AbstractDao<CRResultTypeModel, Long> {

    public static final String TABLENAME = "CRRESULT_TYPE_MODEL";

    /**
     * Properties of entity CRResultTypeModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CRKey = new Property(1, long.class, "CRKey", false, "CRKEY");
        public final static Property RTypeContent = new Property(2, String.class, "RTypeContent", false, "RTYPE_CONTENT");
        public final static Property Index = new Property(3, int.class, "index", false, "INDEX");
    }

    private DaoSession daoSession;


    public CRResultTypeModelDao(DaoConfig config) {
        super(config);
    }
    
    public CRResultTypeModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CRRESULT_TYPE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CRKEY\" INTEGER NOT NULL ," + // 1: CRKey
                "\"RTYPE_CONTENT\" TEXT," + // 2: RTypeContent
                "\"INDEX\" INTEGER NOT NULL );"); // 3: index
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CRRESULT_TYPE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CRResultTypeModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCRKey());
 
        String RTypeContent = entity.getRTypeContent();
        if (RTypeContent != null) {
            stmt.bindString(3, RTypeContent);
        }
        stmt.bindLong(4, entity.getIndex());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CRResultTypeModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCRKey());
 
        String RTypeContent = entity.getRTypeContent();
        if (RTypeContent != null) {
            stmt.bindString(3, RTypeContent);
        }
        stmt.bindLong(4, entity.getIndex());
    }

    @Override
    protected final void attachEntity(CRResultTypeModel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CRResultTypeModel readEntity(Cursor cursor, int offset) {
        CRResultTypeModel entity = new CRResultTypeModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // CRKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RTypeContent
            cursor.getInt(offset + 3) // index
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CRResultTypeModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCRKey(cursor.getLong(offset + 1));
        entity.setRTypeContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIndex(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CRResultTypeModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CRResultTypeModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CRResultTypeModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
