package android.zhixun.uiho.com.gissystem.greendao_gen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import android.zhixun.uiho.com.gissystem.flux.models.AchievementModel;
import android.zhixun.uiho.com.gissystem.flux.models.CGSortOneModel;
import android.zhixun.uiho.com.gissystem.flux.models.CGSortTwoModel;
import android.zhixun.uiho.com.gissystem.flux.models.CQPrefectureModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRActiveUserModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRCheckPersonModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRImageModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRResultTypeModel;
import android.zhixun.uiho.com.gissystem.flux.models.CRSubmitServerModel;
import android.zhixun.uiho.com.gissystem.flux.models.IndustryCategoryModel;
import android.zhixun.uiho.com.gissystem.flux.models.UnitModel;
import android.zhixun.uiho.com.gissystem.flux.models.UserModel;

import android.zhixun.uiho.com.gissystem.greendao_gen.AchievementModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CGSortOneModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CGSortTwoModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CQPrefectureModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRActiveUserModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRCheckPersonModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRImageModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRResultTypeModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.CRSubmitServerModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.IndustryCategoryModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.UnitModelDao;
import android.zhixun.uiho.com.gissystem.greendao_gen.UserModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig achievementModelDaoConfig;
    private final DaoConfig cGSortOneModelDaoConfig;
    private final DaoConfig cGSortTwoModelDaoConfig;
    private final DaoConfig cQPrefectureModelDaoConfig;
    private final DaoConfig cRActiveUserModelDaoConfig;
    private final DaoConfig cRCheckPersonModelDaoConfig;
    private final DaoConfig cRImageModelDaoConfig;
    private final DaoConfig cRModelDaoConfig;
    private final DaoConfig cRResultTypeModelDaoConfig;
    private final DaoConfig cRSubmitServerModelDaoConfig;
    private final DaoConfig industryCategoryModelDaoConfig;
    private final DaoConfig unitModelDaoConfig;
    private final DaoConfig userModelDaoConfig;

    private final AchievementModelDao achievementModelDao;
    private final CGSortOneModelDao cGSortOneModelDao;
    private final CGSortTwoModelDao cGSortTwoModelDao;
    private final CQPrefectureModelDao cQPrefectureModelDao;
    private final CRActiveUserModelDao cRActiveUserModelDao;
    private final CRCheckPersonModelDao cRCheckPersonModelDao;
    private final CRImageModelDao cRImageModelDao;
    private final CRModelDao cRModelDao;
    private final CRResultTypeModelDao cRResultTypeModelDao;
    private final CRSubmitServerModelDao cRSubmitServerModelDao;
    private final IndustryCategoryModelDao industryCategoryModelDao;
    private final UnitModelDao unitModelDao;
    private final UserModelDao userModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        achievementModelDaoConfig = daoConfigMap.get(AchievementModelDao.class).clone();
        achievementModelDaoConfig.initIdentityScope(type);

        cGSortOneModelDaoConfig = daoConfigMap.get(CGSortOneModelDao.class).clone();
        cGSortOneModelDaoConfig.initIdentityScope(type);

        cGSortTwoModelDaoConfig = daoConfigMap.get(CGSortTwoModelDao.class).clone();
        cGSortTwoModelDaoConfig.initIdentityScope(type);

        cQPrefectureModelDaoConfig = daoConfigMap.get(CQPrefectureModelDao.class).clone();
        cQPrefectureModelDaoConfig.initIdentityScope(type);

        cRActiveUserModelDaoConfig = daoConfigMap.get(CRActiveUserModelDao.class).clone();
        cRActiveUserModelDaoConfig.initIdentityScope(type);

        cRCheckPersonModelDaoConfig = daoConfigMap.get(CRCheckPersonModelDao.class).clone();
        cRCheckPersonModelDaoConfig.initIdentityScope(type);

        cRImageModelDaoConfig = daoConfigMap.get(CRImageModelDao.class).clone();
        cRImageModelDaoConfig.initIdentityScope(type);

        cRModelDaoConfig = daoConfigMap.get(CRModelDao.class).clone();
        cRModelDaoConfig.initIdentityScope(type);

        cRResultTypeModelDaoConfig = daoConfigMap.get(CRResultTypeModelDao.class).clone();
        cRResultTypeModelDaoConfig.initIdentityScope(type);

        cRSubmitServerModelDaoConfig = daoConfigMap.get(CRSubmitServerModelDao.class).clone();
        cRSubmitServerModelDaoConfig.initIdentityScope(type);

        industryCategoryModelDaoConfig = daoConfigMap.get(IndustryCategoryModelDao.class).clone();
        industryCategoryModelDaoConfig.initIdentityScope(type);

        unitModelDaoConfig = daoConfigMap.get(UnitModelDao.class).clone();
        unitModelDaoConfig.initIdentityScope(type);

        userModelDaoConfig = daoConfigMap.get(UserModelDao.class).clone();
        userModelDaoConfig.initIdentityScope(type);

        achievementModelDao = new AchievementModelDao(achievementModelDaoConfig, this);
        cGSortOneModelDao = new CGSortOneModelDao(cGSortOneModelDaoConfig, this);
        cGSortTwoModelDao = new CGSortTwoModelDao(cGSortTwoModelDaoConfig, this);
        cQPrefectureModelDao = new CQPrefectureModelDao(cQPrefectureModelDaoConfig, this);
        cRActiveUserModelDao = new CRActiveUserModelDao(cRActiveUserModelDaoConfig, this);
        cRCheckPersonModelDao = new CRCheckPersonModelDao(cRCheckPersonModelDaoConfig, this);
        cRImageModelDao = new CRImageModelDao(cRImageModelDaoConfig, this);
        cRModelDao = new CRModelDao(cRModelDaoConfig, this);
        cRResultTypeModelDao = new CRResultTypeModelDao(cRResultTypeModelDaoConfig, this);
        cRSubmitServerModelDao = new CRSubmitServerModelDao(cRSubmitServerModelDaoConfig, this);
        industryCategoryModelDao = new IndustryCategoryModelDao(industryCategoryModelDaoConfig, this);
        unitModelDao = new UnitModelDao(unitModelDaoConfig, this);
        userModelDao = new UserModelDao(userModelDaoConfig, this);

        registerDao(AchievementModel.class, achievementModelDao);
        registerDao(CGSortOneModel.class, cGSortOneModelDao);
        registerDao(CGSortTwoModel.class, cGSortTwoModelDao);
        registerDao(CQPrefectureModel.class, cQPrefectureModelDao);
        registerDao(CRActiveUserModel.class, cRActiveUserModelDao);
        registerDao(CRCheckPersonModel.class, cRCheckPersonModelDao);
        registerDao(CRImageModel.class, cRImageModelDao);
        registerDao(CRModel.class, cRModelDao);
        registerDao(CRResultTypeModel.class, cRResultTypeModelDao);
        registerDao(CRSubmitServerModel.class, cRSubmitServerModelDao);
        registerDao(IndustryCategoryModel.class, industryCategoryModelDao);
        registerDao(UnitModel.class, unitModelDao);
        registerDao(UserModel.class, userModelDao);
    }
    
    public void clear() {
        achievementModelDaoConfig.clearIdentityScope();
        cGSortOneModelDaoConfig.clearIdentityScope();
        cGSortTwoModelDaoConfig.clearIdentityScope();
        cQPrefectureModelDaoConfig.clearIdentityScope();
        cRActiveUserModelDaoConfig.clearIdentityScope();
        cRCheckPersonModelDaoConfig.clearIdentityScope();
        cRImageModelDaoConfig.clearIdentityScope();
        cRModelDaoConfig.clearIdentityScope();
        cRResultTypeModelDaoConfig.clearIdentityScope();
        cRSubmitServerModelDaoConfig.clearIdentityScope();
        industryCategoryModelDaoConfig.clearIdentityScope();
        unitModelDaoConfig.clearIdentityScope();
        userModelDaoConfig.clearIdentityScope();
    }

    public AchievementModelDao getAchievementModelDao() {
        return achievementModelDao;
    }

    public CGSortOneModelDao getCGSortOneModelDao() {
        return cGSortOneModelDao;
    }

    public CGSortTwoModelDao getCGSortTwoModelDao() {
        return cGSortTwoModelDao;
    }

    public CQPrefectureModelDao getCQPrefectureModelDao() {
        return cQPrefectureModelDao;
    }

    public CRActiveUserModelDao getCRActiveUserModelDao() {
        return cRActiveUserModelDao;
    }

    public CRCheckPersonModelDao getCRCheckPersonModelDao() {
        return cRCheckPersonModelDao;
    }

    public CRImageModelDao getCRImageModelDao() {
        return cRImageModelDao;
    }

    public CRModelDao getCRModelDao() {
        return cRModelDao;
    }

    public CRResultTypeModelDao getCRResultTypeModelDao() {
        return cRResultTypeModelDao;
    }

    public CRSubmitServerModelDao getCRSubmitServerModelDao() {
        return cRSubmitServerModelDao;
    }

    public IndustryCategoryModelDao getIndustryCategoryModelDao() {
        return industryCategoryModelDao;
    }

    public UnitModelDao getUnitModelDao() {
        return unitModelDao;
    }

    public UserModelDao getUserModelDao() {
        return userModelDao;
    }

}
